import "beercss"
import "material-dynamic-colors"
import "@utils/theme"
import "@static/css/global.css"
import "@components/register/register-component"
import "@components/common/footer/footer-component"